### ISSUE TITLE
GetFindGroups returns an error

### ISSUE THREAD

**Issue by spara** [pferate/meetup-api#3]
GetFindGroups doesn't seem to be working correctly 

> > > groups = client.GetFindGroups({'text':'Meetup'})
> > > 29/30 (10 seconds remaining)
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/usr/local/lib/python2.7/site-packages/meetup/api.py", line 154, in _call
> > >     return MeetupObject(response.json())
> > >   File "/usr/local/lib/python2.7/site-packages/meetup/api.py", line 34, in __init__
> > >     for key, value in six.iteritems(dictionary):
> > >   File "/Library/Python/2.7/site-packages/six.py", line 599, in iteritems
> > >     return d.iteritems(**kw)
> > > AttributeError: 'list' object has no attribute 'iteritems'

**Comment by pferate** [comment]
Thanks.  I've found the problem and have a working solution.  Needs more testing, but I'll be updating it in the next few days (hopefully).

**Comment by pferate** [comment]
I've added a MeetupObjectList class to handle when responses have multiple, separate items.  It converts the JSON responses to MeetupObject on the fly.
